const tableBody = document.querySelector('tbody')
const adminObjArray = [{id:idGenerator(),name:'david',email:`david@david.com`,password:passwordGenerator()},]
const jsonButtonElement = document.getElementById('jsonButton')
const jsonDisplayInfoElement = document.getElementById('jsonInfo')
const formButtonElement = document.getElementById('new-admin-button')
const adminTableButton = document.getElementById('tableButton')
function showAdminDetails(){
  formButtonElement.style.visibility='visible'
    jsonButtonElement.style.visibility = 'visible'
    jsonButtonElement.innerHTML = 'Show/Update Json Info';
    adminTableButton.onclick = ''
    tableBody.innerHTML = `<tr>
    <td>${adminObjArray[0]['id']}</td>
    <td>${adminObjArray[0]['name']}</td>
    <td>${adminObjArray[0]['email']}</td>
    <td>${adminObjArray[0]['password']}</td>
    </tr>`;



}

function displayJsonInfo(){
    jsonDisplayInfoElement.innerHTML = JSON.stringify(adminObjArray)
    
}

function idGenerator() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
    });
  }

function passwordGenerator(){
    return 'xx4x4x'.replace(/[xy]/g, function(c) {
        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
      });
    }

let currentNewAdminID 
let currentNewAdminPassword 
function displayAdminForm(){
    currentNewAdminID = idGenerator()
    currentNewAdminPassword = passwordGenerator()
    
    document.querySelector('form').style.onsubmit="return false"; 
    document.querySelector('form').innerHTML = `<div class="form-group">
    <br>
    <label for="firstName">First Name</label>

    <input type="text" class="form-control" id='form-first-name' placeholder="First name" required>

  <label for="exampleInputEmail1">Email address</label>
  <input type="email"  class="form-control" id="form-email" aria-describedby="emailHelp" placeholder="Enter email" required>
  <small id="emailHelp" class="form-text text-muted">The ID and Password are automatically generated by a sophisticated AI software to insure maximum security.</small>
</div>
<div class="form-group">
  <label for="exampleInputId1" >ID</label>
  <input type="id" readonly class="form-control" style='background-color:lightgray;' id="exampleInputID1" placeholder=${currentNewAdminID}>
  <label for="exampleInputPassword1">Password</label>
  <input type="password" readonly style='background-color:lightgray;' class="form-control" id="exampleInputPassword1" placeholder=${currentNewAdminPassword}>
</div>
<button type="submit" id='submit' onclick='sendFormData()' class="btn btn-primary">Submit</button>`

}
  
function submitNewAdmin(newAdminObj){
  adminObjArray.push(newAdminObj)
  console.log(newAdminObj);
  let newAdminTableTd = `<tr>
    <td>${newAdminObj['id']}</td>
    <td>${newAdminObj['name']}</td>
    <td>${newAdminObj['email']}</td>
    <td>${newAdminObj['password']}</td>
    </tr>`
  tableBody.insertAdjacentHTML( 'beforeend', newAdminTableTd );
}

const form = document.querySelector('form');
const data = new FormData(form);



let formNewAdminFirstName
let formNewAdminEmail

let submitButton

function resetFormNewAdminIdAndPassword(){
  submitButton = document.getElementById('submit')
  submitButton.style.visibility = 'hidden';
  console.log(document.getElementById('new-admin-button').innerHTML);
  if(document.getElementById('new-admin-button').innerHTML ==='To add another one click here!!'){
    document.getElementById('new-admin-button').innerHTML ='Another One -Dj khaled'
  }else{
    document.getElementById('new-admin-button').innerHTML = 'To add another one click here!!'
  }
  console.log(submitButton);
  

}

function sendFormData(){
  let formNewAdminFirstName = document.getElementById('form-first-name').value
  let formNewAdminEmail = document.getElementById('form-email').value
  if(formNewAdminFirstName && formNewAdminEmail){
    if(String(formNewAdminEmail).includes('@')){
      let newAdminObj = {
        name:formNewAdminFirstName,
        email:formNewAdminEmail,
        id:currentNewAdminID,
        password:currentNewAdminPassword
      };
      submitNewAdmin(newAdminObj);
      resetFormNewAdminIdAndPassword();
    }
  }
}




var text = 'outside';
function logIt(){
    console.log(text);
    // var text = 'inside';
};
logIt();